In [1]:
2+2

4

# NumPy

## - массивы

In [2]:
# import numpy as np

ModuleNotFoundError: No module named 'numpy'

In [3]:
# !pip install numpy

In [4]:
# импорт библиотеки NumPy и даем ему псевдоним np
import numpy as np

In [5]:
# создание списка
my_list = [1,2,3,4]
my_list

[1, 2, 3, 4]

In [6]:
# создание 1-мерного массива (вектора)
np.array(my_list)

array([1, 2, 3, 4])

In [7]:
# создание массива из нулей
z = np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
# атрибут, показывающий тип значений массива
z.dtype

dtype('float64')

In [9]:
# создание массива из 8-битных целых значений
np.zeros(10, dtype="int8")

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [11]:
np.zeros(10, dtype="int").dtype

dtype('int32')

In [12]:
# создание 2-мерного массива из нулей
# форма в виде кортежа или списка
# (количество строк, количество столбцов)
shape = (3, 4)
np.zeros(shape)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
git 